version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      EXECJS_RUNTIME: Disabled
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: chatwoot_production
      POSTGRES_USERNAME: chatwoot_prod
      POSTGRES_PASSWORD: chatwoot_prod
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: chatwoot_prod
      POSTGRES_PASSWORD: chatwoot_prod
      POSTGRES_DB: chatwoot_production
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis_data:/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: chatwoot_production
      POSTGRES_USERNAME: chatwoot_prod
      POSTGRES_PASSWORD: chatwoot_prod
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis

volumes:
  db_data:
  redis_data:
