version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=chatwoot_prod
      - POSTGRES_PASSWORD=chatwoot_prod
      - POSTGRES_DATABASE=chatwoot_production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=chatwoot_prod
      - POSTGRES_PASSWORD=chatwoot_prod
      - POSTGRES_DB=chatwoot_production
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  redis:
    image: 'redis:6.2'
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'

volumes:
  db-data:
  redis-data:
